# -*- coding: utf-8 -*-
"""fastapipredictionmodel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrlrKFvti_bVJVJ9sofjwZGKlaHqNGX6
"""

from fastapi import FastAPI
import joblib
import pandas as pd
import numpy as np

app = FastAPI()

# ── LOAD FILES ───────────────────────
model = joblib.load("mcr_model.joblib")
le = joblib.load("region_encoder.joblib")
df = pd.read_csv("processed_data.csv")

df["Date"] = pd.to_datetime(df["Date"])

FEATURES = [
    'region_enc', 'year', 'month', 'quarter', 'time_idx',
    'sin_month', 'cos_month',
    'SalesVolume',
    'price_lag_1', 'price_lag_3', 'price_lag_6', 'price_lag_12',
    'rolling_avg_12', 'yoy_change',
    'price_trend_3m', 'price_trend_12m',
    'lag_ratio_1_12', 'volume_price_interaction',
    'price_band'
]

# ── HELPER FUNCTIONS ─────────────────

def get_trend(predicted, last_price):
    change_pct = (predicted - last_price) / last_price

    if change_pct > 0.02:
        return "increasing"
    elif change_pct < -0.02:
        return "decreasing"
    else:
        return "stable"


def get_confidence(row):
    yoy = abs(row["yoy_change"])

    if yoy < 0.03:
        return 0.9
    elif yoy < 0.07:
        return 0.75
    elif yoy < 0.12:
        return 0.6
    else:
        return 0.4


def get_affordability(predicted_price, budget):
    if budget is None:
        return None

    if predicted_price <= budget:
        return "affordable"
    elif predicted_price <= budget * 1.1:
        return "slightly_above_budget"
    else:
        return "unaffordable"


def get_decision(trend, confidence, affordability):
    if affordability == "affordable" and trend == "increasing" and confidence >= 0.7:
        return "BUY"
    elif affordability == "unaffordable" and trend == "increasing":
        return "RELOCATE"
    else:
        return "WAIT"


# ── ROUTES ───────────────────────────

@app.get("/")
def home():
    return {"message": "Manchester Housing Prediction API running"}


@app.post("/predict")
def predict(data: dict):

    # ── INPUT VALIDATION ─────────────
    try:
        region = data["region"]
        date = pd.to_datetime(data["date"])
        budget = data.get("budget", None)
    except:
        return {"error": "Invalid input format"}

    # ── CHECK REGION ────────────────
    if region not in df["RegionName"].unique():
        return {"error": "Region not found"}

    region_df = df[df["RegionName"] == region].sort_values("Date")

    # ── GET LATEST HISTORICAL ROW ───
    latest = region_df[region_df["Date"] < date].tail(1)

    if latest.empty:
        return {"error": "Not enough historical data"}

    latest = latest.copy()

    # ── CREATE FEATURES ─────────────

    latest["year"] = date.year
    latest["month"] = date.month
    latest["quarter"] = (date.month - 1)//3 + 1
    latest["time_idx"] = (date.year - 1995) * 12 + date.month

    latest["sin_month"] = np.sin(2 * np.pi * latest["month"] / 12)
    latest["cos_month"] = np.cos(2 * np.pi * latest["month"] / 12)

    latest["region_enc"] = le.transform([region])[0]

    # ── PREDICT ─────────────────────

    X = latest[FEATURES]

    pred_log = model.predict(X)[0]
    predicted_price = float(np.expm1(pred_log))

    # Safety clipping
    predicted_price = float(np.clip(predicted_price, 50000, 500000))

    # ── TREND ───────────────────────
    last_price = float(latest["price_lag_1"].values[0])
    trend = get_trend(predicted_price, last_price)

    # ── CONFIDENCE ──────────────────
    confidence = get_confidence(latest.iloc[0])

    # ── BUDGET LOGIC ────────────────
    affordability = get_affordability(predicted_price, budget)

    decision = get_decision(trend, confidence, affordability)

    # % difference (nice extra feature)
    budget_diff_pct = None
    if budget:
        budget_diff_pct = ((predicted_price - budget) / budget) * 100

    # ── RESPONSE ────────────────────
    return {
        "region": region,
        "date": str(date.date()),
        "predicted_price": round(predicted_price, 2),
        "trend": trend,
        "confidence": confidence,
        "budget": budget,
        "affordability": affordability,
        "decision": decision,
        "budget_difference_pct": round(budget_diff_pct, 2) if budget else None
    }